package littlebreadloaf.bleachreborn.items;

import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import littlebreadloaf.bleachreborn.Names;
import littlebreadloaf.bleachreborn.api.Tools;
import littlebreadloaf.bleachreborn.armor.Armor;
import littlebreadloaf.bleachreborn.items.bankai.BankaiDark;
import littlebreadloaf.bleachreborn.items.bankai.BankaiEarth;
import littlebreadloaf.bleachreborn.items.bankai.BankaiFire;
import littlebreadloaf.bleachreborn.items.bankai.BankaiHeal;
import littlebreadloaf.bleachreborn.items.bankai.BankaiIce;
import littlebreadloaf.bleachreborn.items.bankai.BankaiLight;
import littlebreadloaf.bleachreborn.items.bankai.BankaiLightning;
import littlebreadloaf.bleachreborn.items.bankai.BankaiLunar;
import littlebreadloaf.bleachreborn.items.bankai.BankaiNormal;
import littlebreadloaf.bleachreborn.items.bankai.BankaiPoison;
import littlebreadloaf.bleachreborn.items.bankai.BankaiWater;
import littlebreadloaf.bleachreborn.items.bankai.BankaiWind;
import littlebreadloaf.bleachreborn.items.qglove.ItemSanreiGlove;
import littlebreadloaf.bleachreborn.items.shikai.ShikaiDark;
import littlebreadloaf.bleachreborn.items.shikai.ShikaiEarth;
import littlebreadloaf.bleachreborn.items.shikai.ShikaiFire;
import littlebreadloaf.bleachreborn.items.shikai.ShikaiHeal;
import littlebreadloaf.bleachreborn.items.shikai.ShikaiIce;
import littlebreadloaf.bleachreborn.items.shikai.ShikaiLight;
import littlebreadloaf.bleachreborn.items.shikai.ShikaiLightning;
import littlebreadloaf.bleachreborn.items.shikai.ShikaiLunar;
import littlebreadloaf.bleachreborn.items.shikai.ShikaiNormal;
import littlebreadloaf.bleachreborn.items.shikai.ShikaiPoison;
import littlebreadloaf.bleachreborn.items.shikai.ShikaiWater;
import littlebreadloaf.bleachreborn.items.shikai.ShikaiWind;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;

public class BleachItems
{
    public static Item reiatsu;
    public static Item shinai;
    public static Item zanpakuto;
    public static Item maskshard;
    public static Item quincybow;
    public static Item soulcloth;
    public static Item oremask;
    public static Item menosmask;
    public static Item fishermask;
    public static Item seele;
    public static Item soulquartz;
    public static Item quincypendant;
    public static Item quincyweb;
    public static Item soulsteel;
    public static Item hollowbook;
    public static Item factionSelect;
    public static Item heart;
    public static Item recordAsterisk;
    public static Item recordNumberOne;
    public static Item recordEscalon;
    public static Item shikaifire;
    public static Item shikaiice;
    public static Item shikaiheal;
    public static Item shikaipoison;
    public static Item shikaiearth;
    public static Item shikaiwind;
    public static Item shikailight;
    public static Item shikaidark;
    public static Item shikailightning;
    public static Item shikailunar;
    public static Item shikaiwater;
    public static Item shikainormal;
    public static Item debugItem;
    public static Item servergift;
    public static Item maleuni;
    public static Item femaleuni;
    public static Item hogyoku;
    public static Item refined_reiatsu;
    public static Item visored_essence;
    public static Item reiatsu_pill;
    public static Item reiatsu_pill1;
    public static Item reiatsu_pill2;
    public static Item reiatsu_pill3;
    public static Item reiatsu_pill4;
    public static Item reiatsu_pill5;
    public static Item reiatsu_pill6;
    public static Item bankainormal;
    public static Item bankaidark;
    public static Item bankaiearth;
    public static Item bankaifire;
    public static Item bankaiheal;
    public static Item bankaiice;
    public static Item bankailight;
    public static Item bankailightning;
    public static Item bankailunar;
    public static Item bankaipoison;
    public static Item bankaiwater;
    public static Item bankaiwind;
    public static Item arrancaressence;
    public static Item ginto;
    public static Item ginto_full;
    public static Item sanrei;
    public static Item sanrei_bow;
    public static Item soulcandy;
    public static Item gigai;
    public static Item control;
    public static Item gauntlet;
    public static Item diablo;
    public static Item hairclip;
    public static final CreativeTabs tabBleach;
    
    public static void init() {
        BleachItems.shinai = new ItemShinai(Tools.SHINAI).setTextureName("bleachreborn".toLowerCase() + "shinai");
        BleachItems.reiatsu = new ItemReiatsu().setTextureName("bleachreborn".toLowerCase() + "reiatsu");
        BleachItems.refined_reiatsu = new ItemRefinedReiatsu().setTextureName("bleachreborn".toLowerCase() + ":refined_reiatsu");
        BleachItems.quincybow = new ItemQuincyBow().setTextureName("bleachreborn".toLowerCase() + "quincy_bow").setFull3D();
        BleachItems.zanpakuto = new ItemZanpakuto(Tools.SOUL).setTextureName("bleachreborn".toLowerCase() + "zanpakuto");
        BleachItems.maskshard = new ItemMaskShard().setTextureName("bleachreborn".toLowerCase() + "mask_shard");
        BleachItems.soulcloth = new ItemSoulCloth().setTextureName("bleachreborn".toLowerCase() + "soulcloth");
        BleachItems.oremask = new ItemOreMask().setTextureName("bleachreborn".toLowerCase() + "oremask");
        BleachItems.menosmask = new ItemMenosMask().setTextureName("bleachreborn".toLowerCase() + "menosmask");
        BleachItems.fishermask = new ItemFisherMask().setTextureName("bleachreborn".toLowerCase() + "fishermask");
        BleachItems.seele = new ItemSeeleschneider(Tools.SOUL).setTextureName("bleachreborn".toLowerCase() + Names.SeeleSchneider_Name);
        BleachItems.soulquartz = new ItemSoulQuartz().setTextureName("bleachreborn".toLowerCase() + "soul_quartz");
        BleachItems.quincypendant = new ItemPendant().setTextureName("bleachreborn".toLowerCase() + Names.QuincyPendant_UnlocalizedName);
        BleachItems.quincyweb = new ItemQuincyWebBow().setTextureName("bleachreborn".toLowerCase() + "quincy_web").setFull3D();
        BleachItems.soulsteel = new ItemSoulSteel().setTextureName("bleachreborn".toLowerCase() + "soul_steel");
        BleachItems.hollowbook = new ItemHollowBook().setTextureName("bleachreborn".toLowerCase() + "hollow_book");
        BleachItems.factionSelect = new ItemFactionSelector().setTextureName("bleachreborn".toLowerCase() + "faction_selector");
        BleachItems.heart = new ItemHeart().setTextureName("bleachreborn".toLowerCase() + "heart");
        BleachItems.recordAsterisk = new ItemBleachRecord("bleachreborn".toLowerCase() + ":asterisk").setUnlocalizedName("asterisk").setTextureName("bleachreborn".toLowerCase() + ":record_asterisk");
        BleachItems.recordNumberOne = new ItemBleachRecord("bleachreborn".toLowerCase() + ":NumberOne").setUnlocalizedName("numberone").setTextureName("bleachreborn".toLowerCase() + ":record_NumberOne");
        BleachItems.recordEscalon = new ItemBleachRecord("bleachreborn".toLowerCase() + ":Escalon").setUnlocalizedName("escalon").setTextureName("bleachreborn".toLowerCase() + ":record_Escalon");
        BleachItems.shikaifire = new ShikaiFire(Tools.SHIKAI).setTextureName("bleachreborn".toLowerCase() + Names.ShikaiFire_UnlocalizedName);
        BleachItems.shikaiice = new ShikaiIce(Tools.SHIKAI).setTextureName("bleachreborn".toLowerCase() + Names.ShikaiIce_UnlocalizedName);
        BleachItems.shikaiheal = new ShikaiHeal(Tools.SHIKAI).setTextureName("bleachreborn".toLowerCase() + Names.ShikaiHeal_UnlocalizedName);
        BleachItems.shikaipoison = new ShikaiPoison(Tools.SHIKAI).setTextureName("bleachreborn".toLowerCase() + Names.ShikaiPoison_UnlocalizedName);
        BleachItems.shikaiearth = new ShikaiEarth(Tools.SHIKAI).setTextureName("bleachreborn".toLowerCase() + Names.ShikaiEarth_UnlocalizedName);
        BleachItems.shikaiwind = new ShikaiWind(Tools.SHIKAI).setTextureName("bleachreborn".toLowerCase() + Names.ShikaiWind_UnlocalizedName);
        BleachItems.shikailight = new ShikaiLight(Tools.SHIKAI).setTextureName("bleachreborn".toLowerCase() + Names.ShikaiLight_UnlocalizedName);
        BleachItems.shikaidark = new ShikaiDark(Tools.SHIKAI).setTextureName("bleachreborn".toLowerCase() + Names.ShikaiDark_UnlocalizedName);
        BleachItems.shikailightning = new ShikaiLightning(Tools.SHIKAI).setTextureName("bleachreborn".toLowerCase() + Names.ShikaiLightning_UnlocalizedName);
        BleachItems.shikailunar = new ShikaiLunar(Tools.SHIKAI).setTextureName("bleachreborn".toLowerCase() + Names.ShikaiNormal_UnlocalizedName);
        BleachItems.shikaiwater = new ShikaiWater(Tools.SHIKAI).setTextureName("bleachreborn".toLowerCase() + Names.ShikaiWater_UnlocalizedName);
        BleachItems.shikainormal = new ShikaiNormal(Tools.SHIKAI).setTextureName("bleachreborn".toLowerCase() + Names.ShikaiNormal_UnlocalizedName);
        BleachItems.debugItem = new DebugItem().setUnlocalizedName("debug").setCreativeTab(BleachItems.tabBleach).setTextureName("bleachreborn".toLowerCase() + "test_garganta");
        BleachItems.servergift = new ItemServerGift().setUnlocalizedName("server_gift").setTextureName("bleachreborn".toLowerCase() + ":server_gift");
        BleachItems.maleuni = new ItemMaleUni().setUnlocalizedName("male_uni").setTextureName("bleachreborn".toLowerCase() + ":male_uni");
        BleachItems.femaleuni = new ItemFemaleUni().setUnlocalizedName("female_uni").setTextureName("bleachreborn".toLowerCase() + ":female_uni");
        BleachItems.hogyoku = new ItemHogyoku().setUnlocalizedName("hogyoku").setCreativeTab(BleachItems.tabBleach).setTextureName("bleachreborn".toLowerCase() + ":hogyoku");
        BleachItems.visored_essence = new ItemVisoredEssence().setUnlocalizedName("visored_essence").setCreativeTab(BleachItems.tabBleach).setTextureName("bleachreborn".toLowerCase() + ":visored_essence");
        BleachItems.reiatsu_pill = new ItemReiatsuPill().setUnlocalizedName("reiatsu_pill").setCreativeTab(BleachItems.tabBleach).setTextureName("bleachreborn".toLowerCase() + ":reiatsu_pill");
        BleachItems.reiatsu_pill1 = new ItemReiatsuPillR().setUnlocalizedName("reiatsu_pill1").setCreativeTab(BleachItems.tabBleach).setTextureName("bleachreborn".toLowerCase() + ":reiatsu_pill1");
        BleachItems.reiatsu_pill2 = new ItemReiatsuPillIron().setUnlocalizedName("reiatsu_pill2").setCreativeTab(BleachItems.tabBleach).setTextureName("bleachreborn".toLowerCase() + ":reiatsu_pill2");
        BleachItems.reiatsu_pill3 = new ItemReiatsuPillG().setUnlocalizedName("reiatsu_pill3").setCreativeTab(BleachItems.tabBleach).setTextureName("bleachreborn".toLowerCase() + ":reiatsu_pill3");
        BleachItems.reiatsu_pill4 = new ItemReiatsuPillD().setUnlocalizedName("reiatsu_pill4").setCreativeTab(BleachItems.tabBleach).setTextureName("bleachreborn".toLowerCase() + ":reiatsu_pill4");
        BleachItems.reiatsu_pill5 = new ItemReiatsuPillE().setUnlocalizedName("reiatsu_pill5").setCreativeTab(BleachItems.tabBleach).setTextureName("bleachreborn".toLowerCase() + ":reiatsu_pill5");
        BleachItems.reiatsu_pill6 = new ItemReiatsuPillNS().setUnlocalizedName("reiatsu_pill6").setCreativeTab(BleachItems.tabBleach).setTextureName("bleachreborn".toLowerCase() + ":reiatsu_pill6");
        BleachItems.bankainormal = new BankaiNormal(Tools.BANKAI).setTextureName("bleachreborn".toLowerCase() + ":bankai_normal1");
        BleachItems.bankaidark = new BankaiDark(Tools.BANKAI).setTextureName("bleachreborn".toLowerCase() + ":bankai_dark1");
        BleachItems.bankaiearth = new BankaiEarth(Tools.BANKAI).setTextureName("bleachreborn".toLowerCase() + ":bankai_earth1");
        BleachItems.bankaifire = new BankaiFire(Tools.BANKAI).setTextureName("bleachreborn".toLowerCase() + ":bankai_fire1");
        BleachItems.bankaiheal = new BankaiHeal(Tools.BANKAI).setTextureName("bleachreborn".toLowerCase() + ":bankai_heal1");
        BleachItems.bankaiice = new BankaiIce(Tools.BANKAI).setTextureName("bleachreborn".toLowerCase() + ":bankai_ice1");
        BleachItems.bankailight = new BankaiLight(Tools.BANKAI).setTextureName("bleachreborn".toLowerCase() + ":bankai_light1");
        BleachItems.bankailightning = new BankaiLightning(Tools.BANKAI).setTextureName("bleachreborn".toLowerCase() + ":bankai_lightning1");
        BleachItems.bankailunar = new BankaiLunar(Tools.BANKAI).setTextureName("bleachreborn".toLowerCase() + ":bankai_lunar1");
        BleachItems.bankaipoison = new BankaiPoison(Tools.BANKAI).setTextureName("bleachreborn".toLowerCase() + ":bankai_poison1");
        BleachItems.bankaiwater = new BankaiWater(Tools.BANKAI).setTextureName("bleachreborn".toLowerCase() + ":bankai_water1");
        BleachItems.bankaiwind = new BankaiWind(Tools.BANKAI).setTextureName("bleachreborn".toLowerCase() + ":bankai_wind1");
        BleachItems.ginto = new ItemGinto().setUnlocalizedName("ginto").setTextureName("bleachreborn".toLowerCase() + ":ginto").setCreativeTab(BleachItems.tabBleach);
        BleachItems.ginto_full = new ItemGintoFull().setUnlocalizedName("ginto_full").setTextureName("bleachreborn".toLowerCase() + ":ginto_full").setCreativeTab(BleachItems.tabBleach);
        BleachItems.sanrei = new ItemSanreiGlove().setUnlocalizedName("sanrei_glove").setTextureName("bleachreborn".toLowerCase() + ":sanrei_glove").setCreativeTab(BleachItems.tabBleach);
        BleachItems.sanrei_bow = new ItemSanreiBow().setTextureName("bleachreborn".toLowerCase() + ":sanrei_bow").setFull3D();
        BleachItems.arrancaressence = new ItemArrancarEssence().setUnlocalizedName("arrancar_essence").setCreativeTab(BleachItems.tabBleach).setTextureName("bleachreborn".toLowerCase() + ":arrancar_essence");
        
        BleachItems.soulcandy = new ItemSoulCandy(2, 2, false).setUnlocalizedName("soulcandy").setTextureName("bleachreborn" + ":soulcandy").setCreativeTab(BleachItems.tabBleach);
        BleachItems.gigai = new ItemGigai().setUnlocalizedName("gigai").setTextureName("bleachreborn" + ":gigai").setCreativeTab(tabBleach);
        BleachItems.control = new ItemControl().setUnlocalizedName("control").setTextureName("bleachreborn" + ":control");
        BleachItems.gauntlet = new ItemSoulGauntlet().setUnlocalizedName("gauntlet").setTextureName("bleachreborn" + ":gauntlet").setCreativeTab(tabBleach);
        
        BleachItems.diablo = new ItemDiablo(ToolMaterial.EMERALD).setUnlocalizedName("diablo").setTextureName("bleachreborn" + ":diablo").setCreativeTab(tabBleach);
        BleachItems.hairclip = new ItemHairclip().setUnlocalizedName("hairclip").setTextureName("bleachreborn" + ":hairclip").setCreativeTab(tabBleach);
    }
    
    public static void registerItems() {
        GameRegistry.registerItem(BleachItems.shinai, "Shinai");
        GameRegistry.registerItem(BleachItems.reiatsu, "Reiatsu");
        GameRegistry.registerItem(BleachItems.refined_reiatsu, "Refined Reiatsu");
        GameRegistry.registerItem(BleachItems.quincybow, "Quincy Bow");
        GameRegistry.registerItem(BleachItems.zanpakuto, "Zanpakuto");
        GameRegistry.registerItem(BleachItems.maskshard, "Mask Shard");
        GameRegistry.registerItem(BleachItems.soulcloth, "Soul Cloth");
        GameRegistry.registerItem(BleachItems.oremask, "Ore Hollow Mask");
        GameRegistry.registerItem(BleachItems.menosmask, "Menos Mask");
        GameRegistry.registerItem(BleachItems.fishermask, "Grand Fisher Mask");
        GameRegistry.registerItem(BleachItems.seele, Names.SeeleSchneider_Name);
        GameRegistry.registerItem(BleachItems.soulquartz, "Soul Quartz");
        GameRegistry.registerItem(BleachItems.quincypendant, "Quincy Pendant");
        GameRegistry.registerItem(BleachItems.quincyweb, "Web Quincy Bow");
        GameRegistry.registerItem(BleachItems.soulsteel, "Soul Steel");
        GameRegistry.registerItem(BleachItems.hollowbook, "Hollow Tome");
        GameRegistry.registerItem(BleachItems.factionSelect, "Faction Selector");
        GameRegistry.registerItem(BleachItems.heart, "Heart");
        GameRegistry.registerItem(BleachItems.recordAsterisk, "ASTERISK");
        GameRegistry.registerItem(BleachItems.recordNumberOne, "NUMBER ONE");
        GameRegistry.registerItem(BleachItems.recordEscalon, "ESCALON");
        GameRegistry.registerItem(BleachItems.shikaifire, "Fire Shikai");
        GameRegistry.registerItem(BleachItems.shikaiice, "Ice Shikai");
        GameRegistry.registerItem(BleachItems.shikaiheal, "Heal Shikai");
        GameRegistry.registerItem(BleachItems.shikaipoison, "Poison Shikai");
        GameRegistry.registerItem(BleachItems.shikaiearth, "Earth Shikai");
        GameRegistry.registerItem(BleachItems.shikaiwind, "Wind Shikai");
        GameRegistry.registerItem(BleachItems.shikailight, "Light Shikai");
        GameRegistry.registerItem(BleachItems.shikaidark, "Dark Shikai");
        GameRegistry.registerItem(BleachItems.shikailightning, "Lightning Shikai");
        GameRegistry.registerItem(BleachItems.shikailunar, "Lunar Shikai");
        GameRegistry.registerItem(BleachItems.shikaiwater, "Water Shikai");
        GameRegistry.registerItem(BleachItems.shikainormal, "Normal Shikai");
        GameRegistry.registerItem(BleachItems.debugItem, "Garganta");
        GameRegistry.registerItem(BleachItems.servergift, "Server Gift");
        GameRegistry.registerItem(BleachItems.maleuni, "Male Uniform Gift");
        GameRegistry.registerItem(BleachItems.femaleuni, "Female Uniform Gift");
        GameRegistry.registerItem(BleachItems.hogyoku, "Hogyoku");
        GameRegistry.registerItem(BleachItems.visored_essence, "Visored Essence");
        GameRegistry.registerItem(BleachItems.reiatsu_pill, "Reiatsu Pill");
        GameRegistry.registerItem(BleachItems.reiatsu_pill1, "Reiatsu Pill1");
        GameRegistry.registerItem(BleachItems.reiatsu_pill2, "Reiatsu Pill2");
        GameRegistry.registerItem(BleachItems.reiatsu_pill3, "Reiatsu Pill3");
        GameRegistry.registerItem(BleachItems.reiatsu_pill4, "Reiatsu Pill4");
        GameRegistry.registerItem(BleachItems.reiatsu_pill5, "Reiatsu Pill5");
        GameRegistry.registerItem(BleachItems.reiatsu_pill6, "Reiatsu Pill6");
        GameRegistry.registerItem(BleachItems.bankainormal, "Normal Bankai");
        GameRegistry.registerItem(BleachItems.arrancaressence, "Arrancar Essence");
        GameRegistry.registerItem(BleachItems.bankaidark, "Dark Bankai");
        GameRegistry.registerItem(BleachItems.bankaiearth, "Earth Bankai");
        GameRegistry.registerItem(BleachItems.bankaifire, "Fire Bankai");
        GameRegistry.registerItem(BleachItems.bankaiheal, "Heal Bankai");
        GameRegistry.registerItem(BleachItems.bankaiice, "Ice Bankai");
        GameRegistry.registerItem(BleachItems.bankailight, "Light Bankai");
        GameRegistry.registerItem(BleachItems.bankailightning, "Lightning Bankai");
        GameRegistry.registerItem(BleachItems.bankailunar, "Lunar Bankai");
        GameRegistry.registerItem(BleachItems.bankaipoison, "Poison Bankai");
        GameRegistry.registerItem(BleachItems.bankaiwater, "Water Bankai");
        GameRegistry.registerItem(BleachItems.bankaiwind, "Wind Bankai");
        GameRegistry.registerItem(BleachItems.ginto, "Ginto");
        GameRegistry.registerItem(BleachItems.ginto_full, "Ginto Full");
        GameRegistry.registerItem(BleachItems.sanrei, "Sanrei Glove");
        GameRegistry.registerItem(BleachItems.sanrei_bow, "Sanrei Bow");
        GameRegistry.registerItem(soulcandy, "Soul Candy");
        GameRegistry.registerItem(gigai, "Gigai");
        GameRegistry.registerItem(control, "Control");
        GameRegistry.registerItem(gauntlet, "Gauntlet");
        GameRegistry.registerItem(diablo, "Diablo");
        GameRegistry.registerItem(hairclip, "Hairclip");
    }
    
    static {
        tabBleach = new CreativeTabs("Bleach Mod") {
            @SideOnly(Side.CLIENT)
            public Item getTabIconItem() {
                return Armor.HollowHelmet;
            }
        };
    }
}
