package littlebreadloaf.bleachreborn.render.models;

import net.minecraft.client.model.*;
import net.minecraft.entity.*;
import net.minecraft.util.*;

public class ModelHollowGolem extends ModelBase
{
    ModelRenderer uppertorso;
    ModelRenderer FR_spike;
    ModelRenderer FL_spike;
    ModelRenderer BL_spike;
    ModelRenderer BR_spike;
    ModelRenderer lower_torso;
    ModelRenderer head;
    ModelRenderer mask;
    ModelRenderer upper_arm_R;
    ModelRenderer lower_arm_R;
    ModelRenderer shoulderR;
    ModelRenderer lower_arm_armor_R;
    ModelRenderer armor_R_shoulder;
    ModelRenderer lower_leg_R;
    ModelRenderer upper_leg_R;
    ModelRenderer upper_arm_L;
    ModelRenderer lower_arm_L;
    ModelRenderer shoulderL;
    ModelRenderer lower_arm_armor_L;
    ModelRenderer armor_L_shoulder;
    ModelRenderer lower_leg_L;
    ModelRenderer upper_leg_L;
    
    public ModelHollowGolem() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        (this.uppertorso = new ModelRenderer((ModelBase)this, 64, 0)).addBox(-8.0f, -7.0f, -7.0f, 16, 16, 16);
        this.uppertorso.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.uppertorso.setTextureSize(128, 128);
        this.uppertorso.mirror = true;
        this.setRotation(this.uppertorso, 0.0f, 0.0f, 0.0f);
        (this.FR_spike = new ModelRenderer((ModelBase)this, 71, 0)).addBox(-5.0f, -14.0f, -5.0f, 2, 9, 2);
        this.FR_spike.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.FR_spike.setTextureSize(128, 128);
        this.FR_spike.mirror = true;
        this.setRotation(this.FR_spike, -0.7853982f, -0.3490659f, 0.0f);
        (this.FL_spike = new ModelRenderer((ModelBase)this, 71, 0)).addBox(2.0f, -14.0f, -5.0f, 2, 9, 2);
        this.FL_spike.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.FL_spike.setTextureSize(128, 128);
        this.FL_spike.mirror = true;
        this.setRotation(this.FL_spike, -0.7853982f, 0.3490659f, 0.0f);
        (this.BL_spike = new ModelRenderer((ModelBase)this, 63, 0)).addBox(1.0f, -19.0f, 2.0f, 2, 9, 2);
        this.BL_spike.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.BL_spike.setTextureSize(128, 128);
        this.BL_spike.mirror = true;
        this.setRotation(this.BL_spike, -0.7853982f, 0.2617994f, 0.0f);
        (this.BR_spike = new ModelRenderer((ModelBase)this, 63, 0)).addBox(-4.0f, -19.0f, 2.0f, 2, 9, 2);
        this.BR_spike.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.BR_spike.setTextureSize(128, 128);
        this.BR_spike.mirror = true;
        this.setRotation(this.BR_spike, -0.7853982f, -0.2617994f, 0.0f);
        (this.lower_torso = new ModelRenderer((ModelBase)this, 81, 32)).addBox(-3.0f, 9.0f, -4.0f, 6, 5, 10);
        this.lower_torso.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.lower_torso.setTextureSize(128, 128);
        this.lower_torso.mirror = true;
        this.setRotation(this.lower_torso, 0.0f, 0.0f, 0.0f);
        (this.head = new ModelRenderer((ModelBase)this, 0, 0)).addBox(-5.0f, -7.0f, -5.0f, 10, 10, 10);
        this.head.setRotationPoint(0.0f, -5.0f, -6.0f);
        this.head.setTextureSize(128, 128);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0f, 0.0f, 0.0f);
        (this.mask = new ModelRenderer((ModelBase)this, 0, 21)).addBox(-4.0f, -8.2f, -6.0f, 10, 10, 10);
        this.mask.setRotationPoint(0.0f, -5.0f, -6.0f);
        this.mask.setTextureSize(128, 128);
        this.mask.mirror = true;
        this.setRotation(this.mask, 0.2094395f, 0.7853982f, 0.2094395f);
        (this.upper_arm_R = new ModelRenderer((ModelBase)this, 3, 65)).addBox(-2.0f, 4.0f, 0.0f, 3, 9, 3);
        this.upper_arm_R.setRotationPoint(-10.0f, -6.0f, 0.0f);
        this.upper_arm_R.setTextureSize(128, 128);
        this.upper_arm_R.mirror = true;
        this.setRotation(this.upper_arm_R, 0.0f, 0.0f, 0.2617994f);
        (this.lower_arm_R = new ModelRenderer((ModelBase)this, 0, 79)).addBox(-4.0f, 9.0f, -16.0f, 6, 7, 13);
        this.lower_arm_R.setRotationPoint(-10.0f, -6.0f, 0.0f);
        this.lower_arm_R.setTextureSize(128, 128);
        this.lower_arm_R.mirror = true;
        this.setRotation(this.lower_arm_R, 0.5235988f, 0.0f, 0.2617994f);
        (this.shoulderR = new ModelRenderer((ModelBase)this, 0, 49)).addBox(-5.0f, -3.0f, -2.0f, 7, 7, 7);
        this.shoulderR.setRotationPoint(-10.0f, -6.0f, 0.0f);
        this.shoulderR.setTextureSize(128, 128);
        this.shoulderR.mirror = true;
        this.setRotation(this.shoulderR, 0.0f, 0.0f, 0.0f);
        (this.lower_arm_armor_R = new ModelRenderer((ModelBase)this, 36, 99)).addBox(-4.5f, 8.5f, -16.5f, 7, 8, 14);
        this.lower_arm_armor_R.setRotationPoint(-10.0f, -6.0f, 0.0f);
        this.lower_arm_armor_R.setTextureSize(128, 128);
        this.lower_arm_armor_R.mirror = true;
        this.setRotation(this.lower_arm_armor_R, 0.5235988f, 0.0f, 0.2617994f);
        (this.armor_R_shoulder = new ModelRenderer((ModelBase)this, 38, 81)).addBox(-6.0f, -4.0f, -3.0f, 9, 7, 9);
        this.armor_R_shoulder.setRotationPoint(-10.0f, -6.0f, 0.0f);
        this.armor_R_shoulder.setTextureSize(128, 128);
        this.armor_R_shoulder.mirror = true;
        this.setRotation(this.armor_R_shoulder, 0.0f, 0.0f, 0.0f);
        (this.lower_leg_R = new ModelRenderer((ModelBase)this, 87, 48)).addBox(-4.0f, 4.0f, -7.0f, 6, 9, 8);
        this.lower_leg_R.setRotationPoint(-4.0f, 11.0f, 2.0f);
        this.lower_leg_R.setTextureSize(128, 128);
        this.lower_leg_R.mirror = true;
        this.setRotation(this.lower_leg_R, 0.0f, 0.0f, 0.0f);
        (this.upper_leg_R = new ModelRenderer((ModelBase)this, 68, 48)).addBox(-3.0f, -1.0f, -2.0f, 4, 9, 5);
        this.upper_leg_R.setRotationPoint(-4.0f, 11.0f, 2.0f);
        this.upper_leg_R.setTextureSize(128, 128);
        this.upper_leg_R.mirror = true;
        this.setRotation(this.upper_leg_R, -0.7853982f, 0.0f, 0.0f);
        (this.upper_arm_L = new ModelRenderer((ModelBase)this, 3, 65)).addBox(0.0f, 4.0f, 0.0f, 3, 9, 3);
        this.upper_arm_L.setRotationPoint(10.0f, -6.0f, 0.0f);
        this.upper_arm_L.setTextureSize(128, 128);
        this.upper_arm_L.mirror = true;
        this.setRotation(this.upper_arm_L, 0.0f, 0.0f, -0.2617994f);
        (this.lower_arm_L = new ModelRenderer((ModelBase)this, 0, 79)).addBox(-1.0f, 9.0f, -16.0f, 6, 7, 13);
        this.lower_arm_L.setRotationPoint(10.0f, -6.0f, 0.0f);
        this.lower_arm_L.setTextureSize(128, 128);
        this.lower_arm_L.mirror = true;
        this.setRotation(this.lower_arm_L, 0.5235988f, 0.0f, -0.2617994f);
        (this.shoulderL = new ModelRenderer((ModelBase)this, 0, 49)).addBox(-2.0f, -3.0f, -2.0f, 7, 7, 7);
        this.shoulderL.setRotationPoint(10.0f, -6.0f, 0.0f);
        this.shoulderL.setTextureSize(128, 128);
        this.shoulderL.mirror = true;
        this.setRotation(this.shoulderL, 0.0f, 0.0f, 0.0f);
        (this.lower_arm_armor_L = new ModelRenderer((ModelBase)this, 78, 99)).addBox(-1.5f, 8.5f, -16.5f, 7, 8, 14);
        this.lower_arm_armor_L.setRotationPoint(10.0f, -6.0f, 0.0f);
        this.lower_arm_armor_L.setTextureSize(128, 128);
        this.lower_arm_armor_L.mirror = true;
        this.setRotation(this.lower_arm_armor_L, 0.5235988f, 0.0f, -0.2617994f);
        (this.armor_L_shoulder = new ModelRenderer((ModelBase)this, 0, 99)).addBox(-3.0f, -4.0f, -3.0f, 9, 7, 9);
        this.armor_L_shoulder.setRotationPoint(10.0f, -6.0f, 0.0f);
        this.armor_L_shoulder.setTextureSize(128, 128);
        this.armor_L_shoulder.mirror = true;
        this.setRotation(this.armor_L_shoulder, 0.0f, 0.0f, 0.0f);
        (this.lower_leg_L = new ModelRenderer((ModelBase)this, 87, 48)).addBox(-2.0f, 4.0f, -7.0f, 6, 9, 8);
        this.lower_leg_L.setRotationPoint(4.0f, 11.0f, 2.0f);
        this.lower_leg_L.setTextureSize(128, 128);
        this.lower_leg_L.mirror = true;
        this.setRotation(this.lower_leg_L, 0.0f, 0.0f, 0.0f);
        (this.upper_leg_L = new ModelRenderer((ModelBase)this, 68, 48)).addBox(-1.0f, -1.0f, -2.0f, 4, 9, 5);
        this.upper_leg_L.setRotationPoint(4.0f, 11.0f, 2.0f);
        this.upper_leg_L.setTextureSize(128, 128);
        this.upper_leg_L.mirror = true;
        this.setRotation(this.upper_leg_L, -0.7853982f, 0.0f, 0.0f);
    }
    
    public void render(final Entity entity, final float f, final float f1, final float f2, final float f3, final float f4, final float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.uppertorso.render(f5);
        this.FR_spike.render(f5);
        this.FL_spike.render(f5);
        this.BL_spike.render(f5);
        this.BR_spike.render(f5);
        this.lower_torso.render(f5);
        this.head.render(f5);
        this.mask.render(f5);
        this.upper_arm_R.render(f5);
        this.lower_arm_R.render(f5);
        this.shoulderR.render(f5);
        this.lower_arm_armor_R.render(f5);
        this.armor_R_shoulder.render(f5);
        this.lower_leg_R.render(f5);
        this.upper_leg_R.render(f5);
        this.upper_arm_L.render(f5);
        this.lower_arm_L.render(f5);
        this.shoulderL.render(f5);
        this.lower_arm_armor_L.render(f5);
        this.armor_L_shoulder.render(f5);
        this.lower_leg_L.render(f5);
        this.upper_leg_L.render(f5);
    }
    
    private void setRotation(final ModelRenderer model, final float x, final float y, final float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
    
    public void setRotationAngles(final float f, final float f1, final float f2, final float f3, final float f4, final float f5, final Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.mask.rotateAngleZ = 0.165f;
        this.upper_arm_R.rotateAngleX = MathHelper.cos(f * 0.6662f + 3.1415927f) * 2.0f * f1 * 0.5f;
        this.upper_arm_L.rotateAngleX = MathHelper.cos(f * 0.6662f) * 2.0f * f1 * 0.5f;
        this.upper_arm_R.rotateAngleZ = 0.3f;
        this.upper_arm_L.rotateAngleZ = -0.3f;
        this.lower_arm_R.rotateAngleX = MathHelper.cos(f * 0.6662f + 3.1415927f) * 2.0f * f1 * 0.5f + 0.52f;
        this.lower_arm_L.rotateAngleX = MathHelper.cos(f * 0.6662f) * 2.0f * f1 * 0.5f + 0.52f;
        this.lower_arm_R.rotateAngleZ = 0.27f;
        this.lower_arm_L.rotateAngleZ = -0.27f;
        this.lower_arm_armor_R.rotateAngleX = MathHelper.cos(f * 0.6662f + 3.1415927f) * 2.0f * f1 * 0.5f + 0.52f;
        this.lower_arm_armor_L.rotateAngleX = MathHelper.cos(f * 0.6662f) * 2.0f * f1 * 0.5f + 0.52f;
        this.lower_arm_armor_R.rotateAngleZ = 0.27f;
        this.lower_arm_armor_L.rotateAngleZ = -0.27f;
        this.upper_leg_R.rotateAngleX = (float)(MathHelper.cos(f * 0.6662f) * 1.4f * f1 - 0.75);
        this.upper_leg_L.rotateAngleX = (float)(MathHelper.cos(f * 0.6662f + 3.1415927f) * 1.4f * f1 - 0.75);
        this.upper_leg_R.rotateAngleY = 0.0f;
        this.upper_leg_L.rotateAngleY = 0.0f;
        this.lower_leg_R.rotateAngleX = MathHelper.cos(f * 0.6662f) * 1.4f * f1;
        this.lower_leg_L.rotateAngleX = MathHelper.cos(f * 0.6662f + 3.1415927f) * 1.4f * f1;
        this.lower_leg_R.rotateAngleY = 0.0f;
        this.lower_leg_L.rotateAngleY = 0.0f;
    }
}
